### ISSUE TITLE
スマホで開いたときにHeader、Footerからボタンが消える

### ISSUE THREAD

**Issue by sousuke0422** [AkariNext/www.akarinext.org#13]
![Screenshot_20240311-002011.png](https://github.com/AkariNext/www.akarinext.org/assets/33174568/676be2c0-d273-4d5c-ab35-16a907a2a4d9)

![Screenshot_20240311-002003.png](https://github.com/AkariNext/www.akarinext.org/assets/33174568/f1a1570a-0baf-4840-a13e-8f6c895710f0)

手元のpixel 6aとiphone 15proで確認

**Comment by yupix** [comment]
どちらも仕様(モバイルより先にブログとかの機能を優先したため)

**Comment by sousuke0422** [comment]
あーね

~~スマホのアプリで上げたら画像でかすぎ~~

**Comment by yupix** [comment]
seyana

**Comment by yupix** [comment]
resolve 14c13f3

**Comment by yupix** [comment]
と思ったけど、これFooterもだった

**Comment by yupix** [comment]
PC
![image](https://github.com/AkariNext/www.akarinext.org/assets/50538210/afa6880f-59ae-4699-a79f-5f03bed8e3fe)

スマホ
![image](https://github.com/AkariNext/www.akarinext.org/assets/50538210/47176f60-ca26-4b3d-aaf0-819f2b54057c)

**Comment by yupix** [comment]
明日直す
