### ISSUE TITLE
別ブランチへのpushがおかしくならないか確認する

### ISSUE THREAD

**Issue by yupix** [AkariNext/www.akarinext.org#15]
force pushが必要そうならアクション変更しないとかも(kustomization弄らなければ多分大丈夫)

**Comment by yupix** [comment]
@AkariNext/qa 次のコミット次第だから私より先に確認したら閉じてok

**Comment by sousuke0422** [comment]
少し手間だけどブランチ保護機能で意図しないpushを弾いてもいいかも

**Comment by yupix** [comment]
masterでkustomization弄ったら保護したところで壊れるのでは 🤔

**Comment by sousuke0422** [comment]
仮にやるなら先に同期させる必要があると・・・

ならいらないね

**Comment by yupix** [comment]
せやね

**Comment by yupix** [comment]
説明が足りてない気がするから詳細を書くと、CIで自動的にkustomizationのimageが変更されるようにしたからそのブランチが普通にコミットするだけで壊れないか一応確認しようってのがこのIssue

https://github.com/AkariNext/www.akarinext.org/tree/auto-update-kustomization

**Comment by sousuke0422** [comment]
30d7eea3957989237f9ef31a953fd1343b739ea9
https://github.com/AkariNext/www.akarinext.org/actions/runs/8223096968/job/22485366807
👀

**Comment by yupix** [comment]
😇

**Comment by sousuke0422** [comment]
https://github.com/AkariNext/www.akarinext.org/actions/runs/8223117567/job/22485416360
YOSASOU

**Comment by yupix** [comment]
fix 76060c2de3fdf85b92404953658f7e93c34e9cb3

**Comment by yupix** [comment]
argocdの自動同期offだったので直しといた
