### ISSUE TITLE
ESLintからBiomeに乗り換える

### ISSUE THREAD

**Issue by yupix** [AkariNext/www.akarinext.org#153]
Biome自体は入ってるから設定をすることになりSO

**Comment by yupix** [comment]
ESLint系のrenovateのプルリクが溜まってきて邪魔だからそろそろやりたい

**Comment by yupix** [comment]
@sousuke0422 中途半端なとこまでやったから出来たら引き継いでほしい

**Comment by yupix** [comment]
あとはアクション動かないのどうにかする

**Comment by sousuke0422** [comment]
やってみる

**Comment by sousuke0422** [comment]
6db06c59b7694248eb4f0d2d97c89fd333860099 a4f4e5a9d23e503131f8884be0221ade99a829df

done
