### ISSUE TITLE
AkariNextの成り立ちについて記述する

### ISSUE THREAD

**Issue by yupix** [AkariNext/www.akarinext.org#30]
- AkariNextにはPimcServer, OrangeServer, Minecraft Game Networkが大きく含まれていること
- AkariNext内の開発・ゲームチームとしてTeamBlackCrystal, INTEXがあること
- AkariNext内のチームに開発チーム・デザインチーム・建築チーム(Minecraftオンリー)・サポートチームがあること

これらの情報とそこに所属する人をいい感じに表示したい

**Comment by yupix** [comment]
@sousuke0422 内容に関してなんか問題あったら教えて

**Comment by sousuke0422** [comment]
YOSASOU

**Comment by yupix** [comment]
![image](https://github.com/AkariNext/www.akarinext.org/assets/50538210/095b562c-643e-4bd5-b4e6-2aaf855f4190)

Rikkalab...?

**Comment by yupix** [comment]
Rikkalabの利用規約はAkariと同時ってあれだけど、Rikkalabの立ち位置ってどこになるの?

**Comment by sousuke0422** [comment]
あまり意識してなかったかも

**Comment by sousuke0422** [comment]
強いて言えば提供しているインフラの名前...?

**Comment by yupix** [comment]
Akari => Orange => Rikkalab?

**Comment by sousuke0422** [comment]
orangeよりrikkalabの方が上位レイヤー

**Comment by yupix** [comment]
Akari => Rikka => Orange?

**Comment by sousuke0422** [comment]
統合した結果

> ![image](https://private-user-images.githubusercontent.com/50538210/311527260-095b562c-643e-4bd5-b4e6-2aaf855f4190.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwOTEwOTIsIm5iZiI6MTcxMDA5MDc5MiwicGF0aCI6Ii81MDUzODIxMC8zMTE1MjcyNjAtMDk1YjU2MmMtNjQzZS00YmQ1LWI0ZTYtMmFhZjg1NWY0MTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDE3MTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNDY5MTViNWQxZjE5NmY5OTYxZDk1NjIyMzNjZjE5OWU2ZmQ3OWQ5NWYzY2YzY2JhN2YxMjE4YTMzYzI1ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YWtkeOAXkipCEphTpXaOlvfI77gKU7FavaEmajqne1k)
> 
> Rikkalab...?

**Comment by yupix** [comment]
そういうことならこういう感じでいいの?

```
Akari === > Pimc
        |=> Rikka
        |=> MGN
```

**Comment by sousuke0422** [comment]
そうなるかも

**Comment by yupix** [comment]
じゃあ今後はそういう感じで行こう
今度Discord側にもアナウンスしたほうがよさそう 🤔

**Comment by yupix** [comment]
これめんどいしよくわからんから無し
