### ISSUE TITLE
スマホで利用規約を見ると横ずれしている

### ISSUE THREAD

**Issue by yupix** [AkariNext/www.akarinext.org#35]
![Screenshot_2024-03-11-03-24-02-66_d365b52accad0f47adbc08c16219827d.jpg](https://github.com/AkariNext/www.akarinext.org/assets/50538210/5edc5797-e8ac-43d5-9356-531907b6b613)

**Comment by sousuke0422** [comment]
![Screenshot_20240311-233014.png](https://github.com/AkariNext/www.akarinext.org/assets/33174568/5613541b-a6c4-42c8-862d-19f048510f1b)

pixel 6a chrome

**Comment by yupix** [comment]
サイズの都合で2.75倍速ぐらいだけど、一応前とあんまり違和感ない感じで横ずれ起きにくい形で再実装した

https://github.com/AkariNext/www.akarinext.org/assets/50538210/00037217-b1dc-4f33-bc37-a88e49009335

**Comment by yupix** [comment]
直すついでに横幅の調整もしたからスマホの時記事の幅が少し狭かったのも直した

![www akarinext org_](https://github.com/AkariNext/www.akarinext.org/assets/50538210/1bc6d426-7397-4c7a-b85b-3aeed330b3b2)

![localhost_5173_](https://github.com/AkariNext/www.akarinext.org/assets/50538210/32b83405-b184-4d4a-ae72-0bf26830fd5b)
