### ISSUE TITLE
スマホで利用規約から利用規約に移動してもサイドバーが閉じない

### ISSUE THREAD

**Issue by yupix** [AkariNext/www.akarinext.org#43]
2回押すと何故か閉じる、キャッシュが原因かもしれないけどよくわからないしだからと言ってメニュー無いのは不便すぎるから一旦放置

**Comment by sousuke0422** [comment]
再現しないhttps://github.com/AkariNext/www.akarinext.org/assets/33174568/2b947776-04dd-4537-a1c3-bc924a1da3f2

**Comment by yupix** [comment]
これ私のVivaldiがおかしい説あるかも、言われてからEdgeで試したら普通に閉じた

**Comment by yupix** [comment]
Vivaldiもなんか治ったかも...謎、とりあえず再現できなくなったから閉じる
