### ISSUE TITLE
PWAをサポートする（エコシステム待ち）

### ISSUE THREAD

**Issue by yupix** [AkariNext/www.akarinext.org#8]
Viteとエコシステム(ライブラリ)の相性が最高に悪そうで、remix-pwaはそもそも動かないし、vite-plugin-pwaは作者がremix向けのドキュメント作ってくれてそうだから時間を置いてサポートする

**Comment by sousuke0422** [comment]
https://vite-pwa-org.netlify.app/frameworks/remix.html

**Comment by yupix** [comment]
`vite-plugin-pwa` はやってみた感じエラーがいっぱい出て、そもそもページが開けなかったのとexamplesでも同じエラーが出るっていうissueがあったからやめた

**Comment by yupix** [comment]
remix-pwaがいい感じになってたからそっち採用
